
site_name: ai-ensemble-suite
site_url: https://stephengenusa.github.io/ai-ensemble-suite
repo_url: https://github.com/StephenGenusa/ai-ensemble-suite
repo_name: StephenGenusa/ai-ensemble-suite

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_if_no_docstring: false
            heading_level: 3

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Quick Start: guide/quickstart.md
    - Configuration: guide/configuration.md
    - Advanced Usage: guide/advanced.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Collaboration Patterns: examples/collaboration.md
    - Aggregation Strategies: examples/aggregation.md
    - Production Configurations: examples/production.md
  - API Reference:
    - Ensemble: api/ensemble.md
    - Configuration: api/configuration.md
    - Models: api/models.md
    - Collaboration: api/collaboration.md
    - Aggregation: api/aggregation.md
    - Utilities: api/utilities.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
